### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by mishako** [rometools/rome2#1]
### Discussions
 - [x] Java 8 (#2, decided: support both 8 and 7/android)
 - [x] Support of old standards (#3, decided: :+1:) 
 - [x] Single artifact (#4, decided: :+1:)
 - [x] Zero dependencies (#5, decided: :+1: except JSON)
 - [x] Suggested API (#6, decided: :+1:)
 - [x] Feed fetching (#7, decided: :-1:)
 - [x] Code generation (#8, decided: :+1:)
 - [x] Absolute leniency (#9, decided: :+1:)

### Prototype
 - [x] Initial suggestion (#10)

**Comment by mishako** [comment]
Moved to the README.
